import type { ApiSurface } from "./types.ts";

const HTTP_VERBS = ["get", "post", "put", "delete", "patch", "head", "options"];

export const API_SIGNATURES: Record<string, ApiSurface> = {
  axios: {
    root: [
      ...HTTP_VERBS,
      "create",
      "request",
      "all",
      "spread",
      "isAxiosError",
      "isCancel",
      "toFormData",
      "formToJSON",
      "getUri",
      "postForm",
      "putForm",
      "patchForm",
      "interceptors",
      "defaults",
      "AxiosError",
      "AxiosHeaders",
      "CanceledError",
      "CancelToken",
      "HttpStatusCode",
      "VERSION",
    ],
    instances: {
      instance: {
        via: ["create"],
        members: [
          ...HTTP_VERBS,
          "request",
          "getUri",
          "postForm",
          "putForm",
          "patchForm",
          "interceptors",
          "defaults",
        ],
      },
    },
    closed: true,
  },
  express: {
    root: ["(call)", "Router", "static", "json", "urlencoded", "raw", "text", "application"],
    instances: {
      app: {
        via: ["(call)"],
        members: [
          ...HTTP_VERBS,
          "use",
          "all",
          "route",
          "listen",
          "set",
          "engine",
          "param",
          "path",
          "enable",
          "enabled",
          "disable",
          "disabled",
          "locals",
          "mountpath",
          "render",
        ],
      },
      router: {
        via: ["Router"],
        members: [...HTTP_VERBS, "use", "all", "route", "param", "stack"],
      },
    },
    closed: true,
  },
  zod: {
    root: ["z", "ZodError", "ZodType", "ZodSchema", "ZodIssueCode"],
    instances: {
      z: {
        via: [],
        members: [
          "object",
          "string",
          "number",
          "boolean",
          "bigint",
          "date",
          "array",
          "tuple",
          "enum",
          "nativeEnum",
          "union",
          "discriminatedUnion",
          "intersection",
          "literal",
          "record",
          "map",
          "set",
          "optional",
          "nullable",
          "any",
          "unknown",
          "never",
          "void",
          "null",
          "undefined",
          "lazy",
          "coerce",
          "custom",
          "instanceof",
          "promise",
          "function",
          "preprocess",
          "infer",
        ],
      },
    },
    closed: true,
  },
  lodash: {
    root: [
      "map",
      "filter",
      "reduce",
      "forEach",
      "find",
      "findIndex",
      "get",
      "set",
      "has",
      "merge",
      "assign",
      "cloneDeep",
      "clone",
      "debounce",
      "throttle",
      "chunk",
      "uniq",
      "uniqBy",
      "flatten",
      "flattenDeep",
      "groupBy",
      "keyBy",
      "orderBy",
      "sortBy",
      "pick",
      "omit",
      "isEqual",
      "isEmpty",
      "isNil",
      "isString",
      "isNumber",
      "isArray",
      "isObject",
      "isFunction",
      "capitalize",
      "camelCase",
      "kebabCase",
      "snakeCase",
      "startCase",
      "range",
      "sum",
      "sumBy",
      "min",
      "max",
      "minBy",
      "maxBy",
      "take",
      "drop",
      "zip",
      "partition",
      "keys",
      "values",
      "entries",
      "invert",
      "memoize",
      "once",
      "noop",
      "identity",
      "times",
      "random",
      "sample",
      "shuffle",
    ],
    instances: {},
    closed: true,
  },
  "node:fs": {
    root: [
      "readFileSync",
      "writeFileSync",
      "appendFileSync",
      "existsSync",
      "mkdirSync",
      "readdirSync",
      "statSync",
      "lstatSync",
      "rmSync",
      "rmdirSync",
      "unlinkSync",
      "copyFileSync",
      "renameSync",
      "chmodSync",
      "openSync",
      "closeSync",
      "readSync",
      "writeSync",
      "realpathSync",
      "symlinkSync",
      "readlinkSync",
      "mkdtempSync",
      "createReadStream",
      "createWriteStream",
      "watch",
      "watchFile",
      "promises",
      "constants",
      "readFile",
      "writeFile",
      "appendFile",
      "stat",
      "readdir",
      "mkdir",
      "rm",
      "unlink",
      "rename",
      "access",
      "copyFile",
      "exists",
    ],
    instances: {},
    closed: true,
  },
  "node:path": {
    root: [
      "join",
      "resolve",
      "dirname",
      "basename",
      "extname",
      "relative",
      "normalize",
      "isAbsolute",
      "parse",
      "format",
      "sep",
      "delimiter",
      "posix",
      "win32",
      "toNamespacedPath",
    ],
    instances: {},
    closed: true,
  },
};

export function curatedSurface(pkg: string): ApiSurface | undefined {
  const direct = API_SIGNATURES[pkg];
  if (direct) return direct;
  if (!pkg.startsWith("node:")) return API_SIGNATURES[`node:${pkg}`];
  return undefined;
}
